#!/bin/bash

git clone git@github.com:buckheroux/CSV-Analyzer.git
cd CSV-Analyzer
sudo mkdir /Library/Python/2.6/site-packages/csv
sudo cp CSV-Analyzer /Library/Python/2.6/site-packages/csv
ENTRY="alias csv=\"/Library/Python/2.6/site-packages/CSVAnalyzer.py\""
ME=`whoami`
BASH_PRO="/Users/${ME}/.bash_profile"
sudo echo "${ENTRY}" >> $BASH_PRO
rm -rf CSV-Analyzer
